### ISSUE TITLE
Configuration for 6 cameras

### ISSUE THREAD

**Issue by grafoteka** [tu-darmstadt-ros-pkg/image_projection#6]
Hi @Martin-Oehler thank you for sharing this great development. 

I have try the demo test include in the repository and I could play it correctly, but now, I'm trying to configure it for my project but I don't know exactly how to do it. I also read your paper, but it does not include any example, for example, with the BD Spot.

My project involves 6 Logitech webcam C270 to create a 360º panoramic view, for launching the cameras I use the usb_cam ros package. All the cameras are correctly launch and name as follows:

```
/camera/front/image_raw
/camera/front/image_raw/compressed
/camera/front/image_raw/compressed/parameter_descriptions
/camera/front/image_raw/compressed/parameter_updates
/camera/front/image_raw/compressedDepth
/camera/front/image_raw/compressedDepth/parameter_descriptions
/camera/front/image_raw/compressedDepth/parameter_updates
/camera/front/image_raw/theora
/camera/front/image_raw/theora/parameter_descriptions
/camera/front/image_raw/theora/parameter_updates

/camera/front_left/
...
/camera/front_right/
...
/camera/left
...
/camera/rear
...
/camera/rear_left/
...
/camera/rear_right/
...
/camera/right
...
```
In the config folder I have modify the file 'camera360_cameras.yaml' with the full set of cameras:
```
# Used cameras for the projection
cameras:
  - '/front'
  - '/front_left'
  - '/front_right'
  - '/left'
  - '/rear_left'
  - '/rear_right'
  - '/right'

# Topic setup
/camera:
    front:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    front_left:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    front_right:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    left:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    rear:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    rear_left:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    rear_right:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
    right:
      image_topic: image_raw
      camera_info_topic: camera_info_not_used
      extended_camera_info_topic: extended_camera_info
```
But I don't know if I have to modify something in the 'proyections.yaml' or if a I have also to modify something in the 'insta360_3_omni_radtan_calibration' folder, maybe in this folder do I have to include the 6 calibration files for the cameras?
```
camera_360_front.yaml
camera_360_front_left.yaml
camera_360_front_right.yaml
camera_360_left.yaml
camera_360_rear.yaml
camera_360_rear_left.yaml
camera_360_rear_right.yaml
camera_360_right.yaml
```
Or do I have to modify the 'cameras.yaml' file?

Also, I think that I should have to add my own *.urdf.xacro file, is it correct?

Thank you in advance.

Kinds regards,
Jorge

**Comment by grafoteka** [comment]
Hi @Martin-Oehler , thank you for your fast and explained reply. 

Right now, I have create my xacro model (only with three cameras) and obtained the calibration parameters of the three cameras.

Now, I will try to modify correctly the yaml file with the tf tree/urdf. 

Kinds regards,
Jorge

**Comment by Martin-Oehler** [comment]
Hello, thanks for waiting.

You made some progress but there are still some issues with your configuration.

> I have read your article and shows the results with the spot, do you think it is possible to share that configuration? 

Yes, it is possible to share it. I will add it when I find time but don't expect anything soon.

> I have create three camera calibration files at: image_projection_ws/src/image_projection/image_projection_demo/config/insta360_3_omni_radtan_calibration/ each file is like this one:

This is not necessary. The node subscribes to the standard camera_info topics as configured in your `robot_cameras.yaml`.

Does your camera config really match the topic names? In your urdf, the camera is called `camera_front`, in your config it is called `camera_front_left`.

> How can I launch the nodes with pinhole cameras instead of ideal fisheye lens? The launch file only include fisheye lens

There may be a misunderstanding here. This starts one nodelet which will create one projection. You need one nodelet per desired projection. Your example creates an ideal fisheye lense projection, but you can also configure a pinhole projection. The projections are configured in the `projections.yaml`.

> And the projections.yaml file to this:

It may not be clear from the example, but the parameters here are actually private parameters of the nodelets (see above). Therefore, for each namespace in this file, you need a nodelet with a corresponding name. Otherwise, your configuration won't be used.

> No cam image received yet. Can't project. This message is throttled

Does this message appear multiple times? If yes, the wrong topic is subscribed. Make sure, that the camera list in your `robot_cameras.yaml` matches the camera topic names.

**Comment by grafoteka** [comment]
Hi @Martin-Oehler, sorry for the late reply, I was trying to fix the code by myself, but I couldn't.

Yes, the names in `robot_cameras.yaml` match with the base topic names of the image topics.

And sorry for the desired projections in the `projections.yaml` file. Now, I have understand correctly it.

You can download the bag file and the launch and config files from this [link](https://sdle365-my.sharepoint.com/:f:/g/personal/jdeleon_sdle_es/EmnNtc9Q55RAhcOv-5Xbkv0BiyOUPXleXeND-n3ZV9Nk9g?e=Ul10D3).

Thank you,
Jorge

**Comment by Martin-Oehler** [comment]
The camera transforms are missing in tf. Did you maybe forget to record `/tf_static`?

**Comment by grafoteka** [comment]
Hello, sorry I forgot to record it. Here is the [new bag](https://sdle365-my.sharepoint.com/:u:/g/personal/jdeleon_sdle_es/EdWT47fmoBJBoSxbjf7nubYB4EoxgnJCZ6xSYk-RKhZxBg?e=T412DE) with all the topics. 

Anyway, I copy it here:
```
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 56
        nsecs: 465000000
      frame_id: "base_link"
    child_frame_id: "center_link"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - 
    header: 
      seq: 0
      stamp: 
        secs: 56
        nsecs: 465000000
      frame_id: "center_link"
    child_frame_id: "center_optical_frame"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.5
        y: -0.4999999999999999
        z: 0.5
        w: -0.5000000000000001
  - 
    header: 
      seq: 0
      stamp: 
        secs: 56
        nsecs: 465000000
      frame_id: "base_link"
    child_frame_id: "left_link"
    transform: 
      translation: 
        x: 0.0
        y: 0.42
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - 
    header: 
      seq: 0
      stamp: 
        secs: 56
        nsecs: 465000000
      frame_id: "left_link"
    child_frame_id: "left_optical_frame"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.5
        y: -0.4999999999999999
        z: 0.5
        w: -0.5000000000000001
  - 
    header: 
      seq: 0
      stamp: 
        secs: 56
        nsecs: 465000000
      frame_id: "base_link"
    child_frame_id: "right_link"
    transform: 
      translation: 
        x: 0.0
        y: -0.42
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - 
    header: 
      seq: 0
      stamp: 
        secs: 56
        nsecs: 465000000
      frame_id: "right_link"
    child_frame_id: "right_optical_frame"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.5
        y: -0.4999999999999999
        z: 0.5
        w: -0.5000000000000001
---
```

**Comment by grafoteka** [comment]
Hi Martin, thank you for your time and help with my configuration. 

Taking in consideration the mistakes with degrees and rads and its implication in the FoV, I have some new doubts, hope you could help me or tell me any doc to read.

I am using for my project the Logitech webcam C270, which has a diagonal FoV of 55º. I have not found any relation between HFoV and DFoV, but I have approximate a value based on the table publish in this [web](https://www.mvteamcctv.com/es/news/Do-you-know-what-s-the-mean-of-FOV-HFOV-VFOV-DFOV-for-security-cameras.html). So, my HFoV is set to 45 degrees.

But now, I have the doubt in the pinhole projection. How can I set correctly the HFoV, _f_ parameters and resolution of the projection?
- Is the resolution the product of the resolution of the cameras that I have? I have three cameras with a resolution of 800x600, is the resolution of the pinhole projection 2400x600 or it is not related?
- How can I set correctly the _f_ and HFoV of the projection?

The best approximation that I could get is with the following configuration:

**projection_parameters**:
-   image_width: 2400
-   image_height: 600
-   horizontal_fov: 10
-   focal_length: 10

And taking in consideration the values that you specify in your code:
```
  registerParameterFromNamespace(nh, "focal_length", 1, "Focal length", 0, 10);
  registerParameterFromNamespace(nh, "horizontal_fov", 90, "Horizontal field of view in degree", 0, 179);
```

But, still having some errors, for example the image does not fix correctly.
![image](https://user-images.githubusercontent.com/7115092/143053230-794283b4-bc80-40db-9407-68aaf096d977.png)

I think that I have some lack of basic knowledge about cameras, if you cite me any article to read it and learn, would be great.

Thanks in advance. 
Jorge

**Comment by Martin-Oehler** [comment]
> I am using for my project the Logitech webcam C270, which has a diagonal FoV of 55º. I have not found any relation between HFoV and DFoV, but I have approximate a value based on the table publish in this web. So, my HFoV is set to 45 degrees.

If you have calibrated your camera, you can always compute the fov from the calibration (e.g., see [here](https://stackoverflow.com/questions/39992968/how-to-calculate-field-of-view-of-the-camera-from-camera-intrinsic-matrix)).

> But now, I have the doubt in the pinhole projection. How can I set correctly the HFoV, f parameters and resolution of the projection?

hfov: However you like. You can increase it until you leave the field of view of the source cameras and see black bars.

focal length: This won't affect the image directly but the stitching lines. Stitching will never be perfect because this approach is geometry-based and your camera centers don't coincide. You should set this value to the standard operation distance (the distance in which you expect obstacles). If objects are in this distance, the stitching is nearly perfect, otherwise, artifacts will be visible. This can also be mitigated by reducing the base line between cameras.

resolution: This one is non-trivial to get right. Basically, if you want the best image possible, increase the resolution until the image does not get better anymore.

You can play around with all these values directly in rqt_reconfigure, if you haven't seen that.

> But, still having some errors, for example the image does not fix correctly.

Try to adjust the focal length.

**Comment by Martin-Oehler** [comment]
Also in your example, you moved the different cameras in a line. You will get better results if you put them as close together as possible and instead rotate them to face different directions.

**Comment by grafoteka** [comment]
Hi Martin, 

I have try to relocate the cameras, just putting together and rotating them:

  ```
<xacro:property name="y_separation" value="0.1" />
<xacro:property name="yaw_rotation" value="${30*M_PI/180}" />

```
Nevertheless, I don't know why, now I don't get any image. I have modify the xacro file but I can't get any projection.
![default perspective - rqt_001](https://user-images.githubusercontent.com/7115092/143242329-f29286aa-ffda-4f90-9bb8-e5909e0d5e9a.png)
![Gazebo_001](https://user-images.githubusercontent.com/7115092/143242343-2616ee8b-65e7-454f-90ec-5ca55e2f0dea.png)
![image](https://user-images.githubusercontent.com/7115092/143242395-00d06624-764b-4cd7-b24c-a31dec46ae03.png)

**Comment by Martin-Oehler** [comment]
You are receiving an image, but it's just black. You likely configured your projection in a way, that nothing is visible.

**Comment by grafoteka** [comment]
Yes, you are right, I don't know why, but the orientation of the pinhole camera is very estrange. I don't why it is happening if I set it to   pose: [0, 0, 0, 0, 0, 0]

![image](https://user-images.githubusercontent.com/7115092/143246116-2bf27283-9fef-4210-a859-6ae8ed8b7303.png)

**Comment by grafoteka** [comment]
Ok, I don't know why, but suddenly at home, it seems to work correctly.
![image](https://user-images.githubusercontent.com/7115092/143302693-8087160e-fa0f-49c2-8e5d-67a89a81ccbb.png)

I think that know I should have to study how to generate correctly the fisheye projections, but at least the pinhole and mercator projections are good.

**Comment by grafoteka** [comment]
Hello Martin, I'm back with new problems... :/

I'm trying now to implement the code with the real cameras, the problem is that I can see the individual images, but the projections fail. 

![image](https://user-images.githubusercontent.com/7115092/143555270-dfb70e37-9ce7-49cf-9c51-fc427cb7d6ef.png)

Also, I attach the TFs 
```
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1637917140
        nsecs: 581428845
      frame_id: "base_link"
    child_frame_id: "fc_link"
    transform: 
      translation: 
        x: 0.05
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1637917140
        nsecs: 581435657
      frame_id: "fc_link"
    child_frame_id: "fc_optical_frame"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.5
        y: -0.4999999999999999
        z: 0.5
        w: -0.5000000000000001
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1637917140
        nsecs: 581436490
      frame_id: "base_link"
    child_frame_id: "fl_link"
    transform: 
      translation: 
        x: 0.025
        y: 0.025
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.38268343236508984
        w: 0.9238795325112867
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1637917140
        nsecs: 581436974
      frame_id: "fl_link"
    child_frame_id: "fl_optical_frame"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.5
        y: -0.4999999999999999
        z: 0.5
        w: -0.5000000000000001
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1637917140
        nsecs: 581437355
      frame_id: "base_link"
    child_frame_id: "fr_link"
    transform: 
      translation: 
        x: 0.025
        y: -0.025
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: -0.38268343236508984
        w: 0.9238795325112867
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1637917140
        nsecs: 581438511
      frame_id: "fr_link"
    child_frame_id: "fr_optical_frame"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.5
        y: -0.4999999999999999
        z: 0.5
        w: -0.5000000000000001
---
```
Also, if I pass my hand in front of the cameras, the tone of the gray changes, but no image is shown.

**Comment by grafoteka** [comment]
Hi Martin, I'm back with some new problems... but I think they are very similar to some previous nevertheless, I can't solve them. 

I'm trying to configure the pinhole projection, the three cameras have the same resolution: 320x240 and are placed symmetrically respect the origin. 

```
  <xacro:property name="x_resolution" value="320" />
  <xacro:property name="y_resolution" value="240" />
  <xacro:property name="horizontal_fov" value="60" />
  <xacro:property name="image_format" value="R8G8B8" />
  <xacro:property name="y_separation" value="0.1" />
  <xacro:property name="x_separation" value="0.0" />
  <xacro:property name="yaw_rotation" value="${25*M_PI/180}" />
  <link name="base_link"/>
  <xacro:real_camera name="fc" parent="base_link" ros_topic="image_raw" cam_info_topic="camera_info" update_rate="10" res_x="${x_resolution}" res_y="${y_resolution}" image_format="${image_format}" hfov="${horizontal_fov}">
    <origin xyz="${0} 0 0" rpy="0.0 0 0"/> 
  </xacro:real_camera>

  <xacro:real_camera name="fl" parent="base_link" ros_topic="image_raw" cam_info_topic="camera_info" update_rate="10" res_x="${x_resolution}" res_y="${y_resolution}" image_format="${image_format}" hfov="${horizontal_fov}">
    <origin xyz="${x_separation} ${y_separation} 0" rpy="0.0 0 ${yaw_rotation}"/> 
  </xacro:real_camera>

  <xacro:real_camera name="fr" parent="base_link" ros_topic="image_raw" cam_info_topic="camera_info" update_rate="10" res_x="${x_resolution}" res_y="${y_resolution}" image_format="${image_format}" hfov="${horizontal_fov}">
    <origin xyz="${x_separation} -${y_separation} 0" rpy="0.0 0 -${yaw_rotation}"/> 
  </xacro:real_camera>
```
But, in the projection, there are some mistakes, the main one is that they don't have the same size. I have verified the /camera_info and the three have 320x240 image_size. If I increase the fov of my cameras, nothing happens.

![pinhole_fail](https://user-images.githubusercontent.com/7115092/143578280-65675f96-7bd6-41b7-b616-30a548a5837d.png)

**Comment by Martin-Oehler** [comment]
> But, in the projection, there are some mistakes, the main one is that they don't have the same size. 

What is the pose of your projection frame? It seems like it is not aligned with your center camera (which I assume you want to do).

> If I increase the fov of my cameras, nothing happens.

Do you mean the parameters of the xacro script? Those only affect the simulated camera. The FOV of your cameras is determined by the optical system of your real cameras.

**Comment by grafoteka** [comment]
> What is the pose of your projection frame? It seems like it is not aligned with your center camera (which I assume you want to do).
The projection frame is also at the origin
```
pinhole_front:
  update_rate: 10
  always_recompute_mapping: false
  base_frame: base_link #$(arg camera_name)_link
  pose: [0, 0, 0, 0, 0, 0]
  virtual_sensor_frame: pinhole_front_camera_frame
  virtual_sensor_optical_frame: pinhole_front_optical_frame
```
> Do you mean the parameters of the xacro script? Those only affect the simulated camera. The FOV of your cameras is determined by the optical system of your real cameras.

You are true, big mistake by my self.
